export default {
  overview: "Visão Geral",
  conventions: "Convenções de Resposta",
  "---Reference": {
    type: "separator",
    title: "Dados de Referência",
  },
  sports: "Esportes",
  leagues: "Ligas",
  sportsbooks: "Casas de Apostas",
  markets: "Mercados",
  "---Odds": {
    type: "separator",
    title: "Odds",
  },
  odds: "Snapshot de Odds",
  "odds-delta": "Delta de Odds",
  "odds-best": "Melhores Odds",
  "odds-comparison": "Comparação de Odds",
  "odds-batch": "Odds em Lote",
  "odds-closing": "Linha de Fechamento",
  "---Teams": {
    type: "separator",
    title: "Times",
  },
  teams: "Times",
  "---Events": {
    type: "separator",
    title: "Eventos",
  },
  events: "Eventos",
  "events-by-id": "Detalhes do Evento",
  "events-odds": "Odds do Evento",
  "events-markets": "Mercados do Evento",
  "---Splits": {
    type: "separator",
    title: "Distribuição de Apostas",
  },
  splits: "Distribuição de Apostas",
  "---LiveGameState": {
    type: "separator",
    title: "Estado do Jogo ao Vivo",
  },
  gamestate: "Estado do Jogo ao Vivo",
  "---Opportunities": {
    type: "separator",
    title: "Oportunidades",
  },
  "opportunities-ev": "Oportunidades +EV",
  "opportunities-arbitrage": "Arbitragem",
  "opportunities-middles": "Middles",
  "opportunities-middles-summary": "Resumo de Middles",
  "opportunities-low-hold": "Low Hold",
  "---DeepLinks": {
    type: "separator",
    title: "Deep Links",
  },
  deeplinks: "Deep Links",
  "---Streaming": {
    type: "separator",
    title: "Streaming",
  },
  stream: "Stream SSE",
  websocket: "Stream WebSocket",
  "---Account": {
    type: "separator",
    title: "Conta",
  },
  account: "Informações da Conta",
  "account-usage": "Estatísticas de Uso",
  "account-keys": "Gerenciamento de API Keys",
  "---Historical": {
    type: "separator",
    title: "Histórico (Sharp+)",
  },
  "historical-clv": "Closing Line Value (CLV)",
  "historical-odds-closing": "Odds de Fechamento por Data",
  "---Enterprise": {
    type: "separator",
    title: "Enterprise",
  },
  enterprise: "Endpoints Enterprise",
  "---Internal": {
    type: "separator",
    title: "Interno",
  },
  health: "Health Check",
}
