export default {
  overview: "Übersicht",
  conventions: "Antwortkonventionen",
  "---Reference": {
    type: "separator",
    title: "Referenzdaten",
  },
  sports: "Sportarten",
  leagues: "Ligen",
  sportsbooks: "Sportsbooks",
  markets: "Märkte",
  "---Odds": {
    type: "separator",
    title: "Quoten",
  },
  odds: "Quoten-Snapshot",
  "odds-delta": "Quoten-Delta",
  "odds-best": "Beste Quoten",
  "odds-comparison": "Quotenvergleich",
  "odds-batch": "Batch-Quoten",
  "odds-closing": "Schlussquote",
  "---Teams": {
    type: "separator",
    title: "Teams",
  },
  teams: "Teams",
  "---Events": {
    type: "separator",
    title: "Events",
  },
  events: "Events",
  "events-by-id": "Event-Details",
  "events-odds": "Event-Quoten",
  "events-markets": "Event-Märkte",
  "---Splits": {
    type: "separator",
    title: "Wettverteilung",
  },
  splits: "Wettverteilung",
  "---LiveGameState": {
    type: "separator",
    title: "Live-Spielstand",
  },
  gamestate: "Live-Spielstand",
  "---Opportunities": {
    type: "separator",
    title: "Möglichkeiten",
  },
  "opportunities-ev": "+EV-Möglichkeiten",
  "opportunities-arbitrage": "Arbitrage",
  "opportunities-middles": "Middles",
  "opportunities-middles-summary": "Middles-Zusammenfassung",
  "opportunities-low-hold": "Low Hold",
  "---DeepLinks": {
    type: "separator",
    title: "Deep Links",
  },
  deeplinks: "Deep Links",
  "---Streaming": {
    type: "separator",
    title: "Streaming",
  },
  stream: "SSE-Stream",
  websocket: "WebSocket-Stream",
  "---Account": {
    type: "separator",
    title: "Konto",
  },
  account: "Kontoinformationen",
  "account-usage": "Nutzungsstatistiken",
  "account-keys": "API-Key-Verwaltung",
  "---Historical": {
    type: "separator",
    title: "Historisch (Sharp+)",
  },
  "historical-clv": "Closing Line Value (CLV)",
  "historical-odds-closing": "Schlussquoten nach Datum",
  "---Enterprise": {
    type: "separator",
    title: "Enterprise",
  },
  enterprise: "Enterprise-Endpoints",
  "---Internal": {
    type: "separator",
    title: "Intern",
  },
  health: "Health Check",
}
