export default {
  overview: "Overview",
  "---Reference": {
    type: "separator",
    title: "Reference Data",
  },
  sports: "Sports",
  leagues: "Leagues",
  sportsbooks: "Sportsbooks",
  markets: "Markets",
  "---Odds": {
    type: "separator",
    title: "Odds",
  },
  odds: "Odds Snapshot",
  "odds-delta": "Odds Delta",
  "odds-best": "Best Odds",
  "odds-comparison": "Odds Comparison",
  "odds-batch": "Batch Odds",
  "---Teams": {
    type: "separator",
    title: "Teams",
  },
  teams: "Teams",
  "---Events": {
    type: "separator",
    title: "Events",
  },
  events: "Events",
  "events-by-id": "Event Details",
  "events-odds": "Event Odds",
  "events-markets": "Event Markets",
  "---Opportunities": {
    type: "separator",
    title: "Opportunities",
  },
  "opportunities-ev": "+EV Opportunities",
  "opportunities-arbitrage": "Arbitrage",
  "opportunities-middles": "Middles",
  "opportunities-middles-summary": "Middles Summary",
  "opportunities-low-hold": "Low Hold",
  "---Streaming": {
    type: "separator",
    title: "Streaming",
  },
  stream: "SSE Stream",
  websocket: "WebSocket Stream",
  "---Account": {
    type: "separator",
    title: "Account",
  },
  account: "Account Info",
  "account-usage": "Usage Stats",
  "account-keys": "API Key Management",
  "---Internal": {
    type: "separator",
    title: "Internal",
  },
  health: "Health Check",
}
