export default {
  overview: "Resumen",
  conventions: "Convenciones de respuesta",
  "---Reference": {
    type: "separator",
    title: "Datos de referencia",
  },
  sports: "Deportes",
  leagues: "Ligas",
  sportsbooks: "Casas de apuestas",
  markets: "Mercados",
  "---Odds": {
    type: "separator",
    title: "Cuotas",
  },
  odds: "Instantánea de cuotas",
  "odds-delta": "Delta de cuotas",
  "odds-best": "Mejores cuotas",
  "odds-comparison": "Comparación de cuotas",
  "odds-batch": "Cuotas por lotes",
  "odds-closing": "Línea de cierre",
  "---Teams": {
    type: "separator",
    title: "Equipos",
  },
  teams: "Equipos",
  "---Events": {
    type: "separator",
    title: "Eventos",
  },
  events: "Eventos",
  "events-by-id": "Detalles del evento",
  "events-odds": "Cuotas del evento",
  "events-markets": "Mercados del evento",
  "---Splits": {
    type: "separator",
    title: "Reparto de apuestas",
  },
  splits: "Reparto de apuestas",
  "---LiveGameState": {
    type: "separator",
    title: "Estado del partido en directo",
  },
  gamestate: "Estado del partido en directo",
  "---Opportunities": {
    type: "separator",
    title: "Oportunidades",
  },
  "opportunities-ev": "Oportunidades +EV",
  "opportunities-arbitrage": "Arbitraje",
  "opportunities-middles": "Middles",
  "opportunities-middles-summary": "Resumen de middles",
  "opportunities-low-hold": "Low Hold",
  "---DeepLinks": {
    type: "separator",
    title: "Deep links",
  },
  deeplinks: "Deep links",
  "---Streaming": {
    type: "separator",
    title: "Streaming",
  },
  stream: "Stream SSE",
  websocket: "Stream WebSocket",
  "---Account": {
    type: "separator",
    title: "Cuenta",
  },
  account: "Información de la cuenta",
  "account-usage": "Estadísticas de uso",
  "account-keys": "Gestión de API keys",
  "---Historical": {
    type: "separator",
    title: "Histórico (Sharp+)",
  },
  "historical-clv": "Closing Line Value (CLV)",
  "historical-odds-closing": "Cuotas de cierre por fecha",
  "---Enterprise": {
    type: "separator",
    title: "Enterprise",
  },
  enterprise: "Endpoints Enterprise",
  "---Internal": {
    type: "separator",
    title: "Interno",
  },
  health: "Comprobación de estado",
}
